# Generated by Django 5.1.2 on 2024-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(choices=[('sin salsas', 'sin Salsas'), ('con todas las salsas', 'Con Todas las Salsas'), ('sin salsa blanca', 'Sin Salsa Blanca'), ('con salsa blanca', 'Con Sslsa Blanca'), ('con mostaza', 'Con Mostaza'), ('sin mostaza', 'Sin Mostaza'), ('sin salsa roja', 'Sin Salsa Roja'), ('con salsa roja', 'Con Salsa Roja'), ('sin cebolla', 'Sin Cebolla'), ('sin pepinillos', 'Sin Pepinillos')], default='sin salsas', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('parallevar', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=50)),
                ('estado', models.CharField(choices=[('espera', 'En Espera'), ('preparacion', 'En Preparación'), ('terminado', 'Terminado')], default='espera', max_length=50)),
                ('nombre_cliente', models.CharField(default='Cliente 1', max_length=50)),
            ],
        ),
    ]
